### ISSUE TITLE
Deprecation: ec2_ami_search may need to be amended

### ISSUE THREAD

**Issue by aaronpederson** [telusdigital/ansible-aws-infrastructure#55]
TASK [telusdigital.aws-infrastructure : include] *******************************
[DEPRECATION WARNING]: ec2_ami_search is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale..
This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
included: /private/etc/ansible/roles/telusdigital.aws-infrastructure/tasks/create/instance.yml for localhost

**Comment by noqcks** [comment]
This has been deprecated in 2.0 in favour of the `ec2_ami_find` module.

**Comment by noqcks** [comment]
was implemented in https://github.com/telusdigital/ansible-aws-infrastructure/pull/57
